### ISSUE TITLE
"cos put" node is showing error triangle although it works

### ISSUE THREAD

**Issue by hseipp** [O-Hahn/node-red-contrib-cos#1]
I'm using a Node-RED instance on the IBM Cloud and configured node-red-contrib-cos with IAM credentials for my (EU-GB-based) COS instance. The get, delete and search node do not show any error and work as expected, but the put node (configured with msg.payload mode and text/plain mimetype) shows an error triangle although I can successfully upload objects:
![image](https://user-images.githubusercontent.com/20093686/42025168-37713300-7ac4-11e8-94b3-ce19d4d1cfd8.png)

**Comment by hseipp** [comment]
I found the root cause and a fix: in msg.payload mode, file name is not used, thus it must not be flagged as "required" - here is the according patch:

```
--- cos.html.orig	2018-06-28 13:56:02.795421326 +0200
+++ cos.html	2018-06-28 13:56:13.571316878 +0200
@@ -301,7 +301,7 @@
             objectname: {value:"", required:false},
             mode: {value:"0", required:true},
             filepath: {value:"", required:false},
-            filename: {value:"", required:true},
+            filename: {value:"", required:false},
             contentType: {value:"", required:true},
             geturl: {value:false, required:false},
             cosconfig: {value:"", type:"cos-config", required:true}
```

**Comment by O-Hahn** [comment]
ok done
