### ISSUE TITLE
Configuration Documentation

### ISSUE THREAD

**Issue by tim-minter** [O-Hahn/node-red-contrib-cos#17]
I'm fairly familiar with everything IBM Cloud however I'm unable to configure the nodes because I can't figure out what the Service Instance ID should be (from the Cloud Object Storage credentials that are generated today) or if the Authority Endpoint (https://iam.ng.bluemix.net/oidc/token) is still correct? Could we have some documentation on steps to populate the config node using the COS service as it is today? Cheers.

**Comment by tonyngmk** [comment]
Same here, can anyone further elaborate on the configuration, please?

**Comment by tim-minter** [comment]
{
  "apikey": "xxxxxx",
  "cos_hmac_keys": {
    "access_key_id": "xxxxx",
    "secret_access_key": "xxxxx"
  },
  "endpoints": "https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints",
  "iam_apikey_description": "Auto-generated for key xxxxxx",
  "iam_apikey_name": "TestCredentials",
  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/xxxxxx::serviceid:ServiceId-xxxxxx",
  "resource_instance_id": "crn:v1:bluemix:public:cloud-object-storage:global:a/xxxx-xxx-xxx-xxx-xx::"
}

The IBM Cloud Object Service gives you something like the above...
Yes so the Authority Endpoint is https://iam.ng.bluemix.net/oidc/token
The service instance id is the **resource_instance_id** and the region is one thing that caused me problems. Try the options until you find the right one. Also another gotcha is the node itself says "initialising" even if it connected ok _until_ you send it a query. I thought I had a problem for some time but didn't in reality.

**Comment by hseipp** [comment]
You'll get the region (as of node-red-contrib-cos 0.0.19 the config node now consistently labels it "location") from your Cloud Object Storage bucket listing within the IBM Cloud UI - look for the "Location" column. Obviously your Node-RED usage is limited to buckets that are deployed in this particular region/location.

**Comment by O-Hahn** [comment]
link to new endpoints and also iam implemented by default. New version available.
