### ISSUE TITLE
cos-del node error

### ISSUE THREAD

**Issue by Oktober31** [O-Hahn/node-red-contrib-cos#18]
Hello,

I use your project to try to use IBM storage. Very good project.

But I have a problem whith cos-del node  
![image](https://user-images.githubusercontent.com/40166111/94907235-1e073780-04a0-11eb-9164-efd13234f485.png)

But when the msg.objectname is good and coming from the node before, it's OK.

Is it possible to correct ?

Thank you.

OB

**Comment by O-Hahn** [comment]
Hi - i am sorry - i don´t understand your problem. Whats going wrong? 
Do you delete the object by setting msg.objectname and than it is not deleted - or do you want to set the object-name in the node - and it is not deleted ?

**Comment by Oktober31** [comment]
![image](https://user-images.githubusercontent.com/40166111/94921250-35521f00-04b8-11eb-8d39-eee0bdbfd23f.png)
In the first node, I write the variable msg.objectname.

But the objectname is mandatory in the cos-del node. So you can see it gives an error. And then each time I save my project, I have a popup with a message to say I have an error.

Excuse my english.

**Comment by Oktober31** [comment]
![image](https://user-images.githubusercontent.com/40166111/94921553-d50fad00-04b8-11eb-933b-18f31a9e952e.png)
But the cos-del node is functionning.

**Comment by burtonboucher** [comment]
Delete node Object Name appears to be a required configuration field. Object Name should be optional configuration, I believe is the request.

Oktober31 can you configure Object Name in Del Node? Your code is overriding msg.objectname so this should allow your code to operate and eliminate configuration warning.

**Comment by Oktober31** [comment]
Thank you. It’s OK.

De : Burton Boucher <notifications@github.com>
Envoyé : vendredi 2 octobre 2020 15:56
À : O-Hahn/node-red-contrib-cos <node-red-contrib-cos@noreply.github.com>
Cc : Olivier Brombacher <Olivier.Brombacher@eureka-solutions.fr>; Author <author@noreply.github.com>
Objet : Re: [O-Hahn/node-red-contrib-cos] cos-del node error (#18)


Delete node Object Name appears to be a required configuration field. Object Name should be optional configuration, I believe is the request.

Oktober31 can you configure Object Name in Del Node? Your code is overriding msg.objectname so this should allow your code to operate and eliminate configuration warning.

**Comment by Oktober31** [comment]
Tahk you for your answer.
