### ISSUE TITLE
IBM COS endpoint is hard-coded, no way to change

### ISSUE THREAD

**Issue by dianadujing** [O-Hahn/node-red-contrib-cos#19]
Hi @O-Hahn ,

I was using this plugin in my Node-Red app on IBM Cloud. And I noticed that the endpoint of IBM S3 COS is hard-coded like this: s3.us-east.objectstorage.softlayer.net .

Recently, I received an email notifying that IBM COS endpoint ended with *.objectstorage.softlayer.net will be shutdown by the end of this month, only *.cloud-object-storage.appdomain.cloud will be supported in the future. Can you please update this plugin accordingly or make it configurable?

Thanks,
DJ

**Comment by O-Hahn** [comment]
changed - fixed in new version - also use "manual" - there you can point to your instance manually

**Comment by dianadujing** [comment]
@O-Hahn Thank you! I have unpublished forked lib and left deprecation message on npm.
