### ISSUE TITLE
Problem send mail after update node-red-node-email (1.8.2)

### ISSUE THREAD

**Issue by Oktober31** [O-Hahn/node-red-contrib-cos#22]
Since I update this node my emails always looks like this
![image](https://user-images.githubusercontent.com/40166111/99408791-e558db80-28f0-11eb-85ee-a6cf67e10924.png)

Or I had this result before.
![image](https://user-images.githubusercontent.com/40166111/99408473-901cca00-28f0-11eb-8c1f-9e0f85b4f41f.png)

I searched a long time but I found the problem.

My msg data included headers (msg.headers). This comes from the dashboard page I display before. And now this data create a problem.

I delete this zone from msg and now it is ok.

@knolleary and @dceejay

I hope this information can interest you.

OBR

**Comment by O-Hahn** [comment]
THX for giving me the feedback... I tried with my test-flows but i couldn´t recreate the error.
