### ISSUE TITLE
Configuration Tab info missing

### ISSUE THREAD

**Issue by DrZeta360** [O-Hahn/node-red-contrib-cos#9]
Hi! Let me start thanking you for developing this nodes, they are great!
I updated the node today from 0.0.16 to 0.0.17 and the labels on the configuration tab have disappeared. I tried two different devices and had the same results.
I've uploaded a picture showing the issue.
Thanks!
![COS](https://user-images.githubusercontent.com/26259399/63428683-0f7ecd80-c410-11e9-96d4-8694ec4c8ae2.PNG)

**Comment by bttong** [comment]
Any update on this issue?  I've ran into the same problem.

**Comment by O-Hahn** [comment]
i have found a typo in the last commit of the cos.json for the lables - causes not to load the lables. Fix with the new version - will be published today.

**Comment by DrZeta360** [comment]
That's great, thanks!
